### PR TITLE
Delete CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by comradekingu**
Will contribute if this is removed.
It isn't needed anyhow, and as far as translations go, this very textfile was removed from Weblate without issue in favour of a CONTACT.md file. :)

### CODE REVIEW

**Comment by fmeurou** [comment]
Could you be more explicit as to why we should remove the code of conduct ?

**Comment by comradekingu** [comment]
To put some exasperated merit into my wishes of volunteering my time,

It removes sexuality and other fellow swoops of humanity and community found to be something, and moves interpretation of what that is into the field of non-meritocratic authority. Non-professional indeed! Increasingly so, in a digest of versions.

If I am to be told to apply a different understanding of biology and navigation of social hierarchy there, I will tell you it isn't there to be found in these written unwritten rules to begin with, nor is that understanding anything but a derived concept from the unwritten understanding yet-to-be conveyed. A tautology best avoided in its unappealing nature.

What _is_ to be found is in all its vagueness something only arriving at the capacity of being blunt when it comes to _applying_ justification.

The idea of pledging allegiance to a text-file requiring it on part of ones community with the push of a button is actively preposterous, not in the least because it doesn't even come to that for anyone else. Should anyone actually wish to move the pretending over to their own domain (without it being imposed by a text-file) nobody is even prevented from doing so if it isn't there. It does (not even) nothing.

Then imagine how horrifying the actual need for it would be, and consider understanding or disobeying text-files for the anti-social action or person does nothing for the better about as much. Much like the same intangible premise of its operation somehow being proactive. What it does do for people vulnerable enough to believe in it is carry some premise of doing something when wishful thinking doesn't do anything there either. Theatrical false sense of security.

What actually happens is every time someone pretends on part of other groups there is a problem contributing as a member of one or more of said groups, a greater problem is _created_, not solved. Reactionary without so much as a non-counterproductive point to make.

It is even pretentious enough to apply itself where to harassment, redundant to an actual trifecta of power in measured response and description of it.

Escalating any problem beyond the reproach of someone not or in the wrong is the issue at every level here. Anti-sociality does not a community make, nor does it help society at large or anyone in it. It is the empowerment of egocentricism.

To add injurious insult to its long list of insufferable indignation, the tepidly named "Covenant CoC" even allows variant sections. Of problems to overlook, _hardly anybody reading or remembering it_ isn't even its most inherent _preliminary_ one.

**Comment by comradekingu** [comment]
@fmeurou ?

**Comment by fmeurou** [comment]
Hi, let's agree to disagree for the need of the removal of the Code of Conduct.
In an ideal world that would not be necessary, but unfortunately, a reminder of what's expected to contribute, not only from a code perspective is needed, because we're human.

**Comment by comradekingu** [comment]
@fmeurou

So you think you can expect contributors to make a pledge not to not make sexual advances?
Who are the "we" that is human there?
I will grant you the world is less than ideal, but this is a far cry from human.

If OTOH humans in the capacity of preordained sin need pledge allegiance to professionalism to contribute in this world, it is in the very least beyond recognition for me.
I'll agree there.

We can agree to disagree on the need to instate it too. I will however defend your meritocracy,
by honouring you are in your full right to put up a text-file that tries to undermine such powers.
What I won't do is pretend I agree, or that anyone does. Much less anyone that should care about harassment like anyone thinks they care about a text-file. There is no need to instate it, just like there _shouldn't_ be, and isn't.
Furthermore removing it evidently does nothing. All of which you do about it is truly something. All of which you hopefully would, and could do anyhow.

I am particularly interested in whether you think this is needed:

> Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct

That is a perfect tautology.

You will find "Project maintainers" has been replaced with "Community leaders" in the 2.0 version.

What position could be more sought after for people with inhumane qualities?

CoCs are after all the tool of the mafia and the catholic church, not the libre software ecosystem where none of it was made with one.

>The project team is obligated to maintain confidentiality with regard to the reporter of an incident.
>Focusing on what is best not just for us as individuals, but for the overall community.
> political attacks (under unacceptable behaviour)
> No interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, for a specified period of time. This includes avoiding interactions in community spaces as well as external channels like social media.

The escalation of conflict beyond the control of the person/s involved (or not), with zero accountability, an oath of silence, no political opposition, wielding the tool of permanent bans for disparaging "classes of individuals".

What is that called again?
I am just going to go ahead and call that secret society governance. It comes from people stating a political aim in doing so. Also, it is the erection of a playground for sociopathic people. Because we're human.

Also,

> Focusing on what is best not just for us as individuals, but for the overall community

This unwritten now written rule is now in writing in the 2.0 version.

Does it prevent psychopaths from abusing "community leader" or "project team" however they "deem appropriate"?

Curiously, if not having this CoC is somehow the absence of all the "interest of fostering an open and welcoming environment", does that mean the 1.4 version somehow invokes a problem of egocentricity?
If you tell me 1.4 is needed over nothing, I will present you all the further "evidence" of the self-imposed grandeur of added language in the version taking its place. Why is it not at the latest version, and why isn't it more important to update it?

In the aggregate, how long till someone notices something else isn't actually in there?
An even more bloated 2.1 version that even fewer people even try to read?

**Pull request closed without merging**
